#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContentTypeMaster {
    #[prost(string, tag = "1")]
    pub master_version: ::prost::alloc::string::String,
    #[prost(enumeration = "Type", tag = "2")]
    pub content_type_master_id: i32,
    #[prost(int64, tag = "3")]
    pub content_id: i64,
    #[prost(string, tag = "90")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContentTypeMasters {
    #[prost(message, repeated, tag = "1")]
    pub content_type_masters: ::prost::alloc::vec::Vec<ContentTypeMaster>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Type {
    Invalid = 0,
    Character = 100,
    BattleCharacter = 101,
    Equipment = 102,
    Item = 103,
    Box = 104,
    PickBox = 105,
    Gold = 106,
    Gem = 107,
    Stone = 108,
    Stamina = 110,
    PlayerIconFrame = 112,
    PlayerExp = 113,
    BattleCharacterExpItem = 114,
    GachaTicket1 = 115,
    Background = 116,
    EquipmentExpItem = 117,
    Keyword = 118,
    BattleCharacterBond = 119,
    Energy = 120,
    ExploreCoin = 121,
    DungeonItem = 122,
    StaminaRecoveryItem = 123,
    MissionDailyPoint = 124,
    MissionAchievementPoint = 125,
    MusicRecord = 126,
    TeabreakItem = 127,
    CrusadePoint = 128,
    Phoneme = 129,
    PhonemeBuffItem = 130,
    PhonemeExpItem = 131,
    PhonemeCoin = 132,
    PhonemeConstructItem = 133,
    EquipmentCoin = 134,
    EquipmentRankUpItem = 135,
    UndergroundPoint = 136,
    MonthlyPass = 137,
    BattlePassExp = 138,
    BoxOpenImmediately = 139,
    BattlePass = 140,
    PopGift = 141,
    CreditPoint = 142,
    Badge = 143,
    Disguise = 144,
    DisguiseOwn = 145,
    PaidGem = 201,
    FreeGem = 202,
    PaidStone = 211,
    FreeStone = 212,
    Currency = 999,
}
impl Type {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Type::Invalid => "INVALID",
            Type::Character => "CHARACTER",
            Type::BattleCharacter => "BATTLE_CHARACTER",
            Type::Equipment => "EQUIPMENT",
            Type::Item => "ITEM",
            Type::Box => "BOX",
            Type::PickBox => "PICK_BOX",
            Type::Gold => "GOLD",
            Type::Gem => "GEM",
            Type::Stone => "STONE",
            Type::Stamina => "STAMINA",
            Type::PlayerIconFrame => "PLAYER_ICON_FRAME",
            Type::PlayerExp => "PLAYER_EXP",
            Type::BattleCharacterExpItem => "BATTLE_CHARACTER_EXP_ITEM",
            Type::GachaTicket1 => "GACHA_TICKET_1",
            Type::Background => "BACKGROUND",
            Type::EquipmentExpItem => "EQUIPMENT_EXP_ITEM",
            Type::Keyword => "KEYWORD",
            Type::BattleCharacterBond => "BATTLE_CHARACTER_BOND",
            Type::Energy => "ENERGY",
            Type::ExploreCoin => "EXPLORE_COIN",
            Type::DungeonItem => "DUNGEON_ITEM",
            Type::StaminaRecoveryItem => "STAMINA_RECOVERY_ITEM",
            Type::MissionDailyPoint => "MISSION_DAILY_POINT",
            Type::MissionAchievementPoint => "MISSION_ACHIEVEMENT_POINT",
            Type::MusicRecord => "MUSIC_RECORD",
            Type::TeabreakItem => "TEABREAK_ITEM",
            Type::CrusadePoint => "CRUSADE_POINT",
            Type::Phoneme => "PHONEME",
            Type::PhonemeBuffItem => "PHONEME_BUFF_ITEM",
            Type::PhonemeExpItem => "PHONEME_EXP_ITEM",
            Type::PhonemeCoin => "PHONEME_COIN",
            Type::PhonemeConstructItem => "PHONEME_CONSTRUCT_ITEM",
            Type::EquipmentCoin => "EQUIPMENT_COIN",
            Type::EquipmentRankUpItem => "EQUIPMENT_RANK_UP_ITEM",
            Type::UndergroundPoint => "UNDERGROUND_POINT",
            Type::MonthlyPass => "MONTHLY_PASS",
            Type::BattlePassExp => "BATTLE_PASS_EXP",
            Type::BoxOpenImmediately => "BOX_OPEN_IMMEDIATELY",
            Type::BattlePass => "BATTLE_PASS",
            Type::PopGift => "POP_GIFT",
            Type::CreditPoint => "CREDIT_POINT",
            Type::Badge => "BADGE",
            Type::Disguise => "DISGUISE",
            Type::DisguiseOwn => "DISGUISE_OWN",
            Type::PaidGem => "PAID_GEM",
            Type::FreeGem => "FREE_GEM",
            Type::PaidStone => "PAID_STONE",
            Type::FreeStone => "FREE_STONE",
            Type::Currency => "CURRENCY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVALID" => Some(Self::Invalid),
            "CHARACTER" => Some(Self::Character),
            "BATTLE_CHARACTER" => Some(Self::BattleCharacter),
            "EQUIPMENT" => Some(Self::Equipment),
            "ITEM" => Some(Self::Item),
            "BOX" => Some(Self::Box),
            "PICK_BOX" => Some(Self::PickBox),
            "GOLD" => Some(Self::Gold),
            "GEM" => Some(Self::Gem),
            "STONE" => Some(Self::Stone),
            "STAMINA" => Some(Self::Stamina),
            "PLAYER_ICON_FRAME" => Some(Self::PlayerIconFrame),
            "PLAYER_EXP" => Some(Self::PlayerExp),
            "BATTLE_CHARACTER_EXP_ITEM" => Some(Self::BattleCharacterExpItem),
            "GACHA_TICKET_1" => Some(Self::GachaTicket1),
            "BACKGROUND" => Some(Self::Background),
            "EQUIPMENT_EXP_ITEM" => Some(Self::EquipmentExpItem),
            "KEYWORD" => Some(Self::Keyword),
            "BATTLE_CHARACTER_BOND" => Some(Self::BattleCharacterBond),
            "ENERGY" => Some(Self::Energy),
            "EXPLORE_COIN" => Some(Self::ExploreCoin),
            "DUNGEON_ITEM" => Some(Self::DungeonItem),
            "STAMINA_RECOVERY_ITEM" => Some(Self::StaminaRecoveryItem),
            "MISSION_DAILY_POINT" => Some(Self::MissionDailyPoint),
            "MISSION_ACHIEVEMENT_POINT" => Some(Self::MissionAchievementPoint),
            "MUSIC_RECORD" => Some(Self::MusicRecord),
            "TEABREAK_ITEM" => Some(Self::TeabreakItem),
            "CRUSADE_POINT" => Some(Self::CrusadePoint),
            "PHONEME" => Some(Self::Phoneme),
            "PHONEME_BUFF_ITEM" => Some(Self::PhonemeBuffItem),
            "PHONEME_EXP_ITEM" => Some(Self::PhonemeExpItem),
            "PHONEME_COIN" => Some(Self::PhonemeCoin),
            "PHONEME_CONSTRUCT_ITEM" => Some(Self::PhonemeConstructItem),
            "EQUIPMENT_COIN" => Some(Self::EquipmentCoin),
            "EQUIPMENT_RANK_UP_ITEM" => Some(Self::EquipmentRankUpItem),
            "UNDERGROUND_POINT" => Some(Self::UndergroundPoint),
            "MONTHLY_PASS" => Some(Self::MonthlyPass),
            "BATTLE_PASS_EXP" => Some(Self::BattlePassExp),
            "BOX_OPEN_IMMEDIATELY" => Some(Self::BoxOpenImmediately),
            "BATTLE_PASS" => Some(Self::BattlePass),
            "POP_GIFT" => Some(Self::PopGift),
            "CREDIT_POINT" => Some(Self::CreditPoint),
            "BADGE" => Some(Self::Badge),
            "DISGUISE" => Some(Self::Disguise),
            "DISGUISE_OWN" => Some(Self::DisguiseOwn),
            "PAID_GEM" => Some(Self::PaidGem),
            "FREE_GEM" => Some(Self::FreeGem),
            "PAID_STONE" => Some(Self::PaidStone),
            "FREE_STONE" => Some(Self::FreeStone),
            "CURRENCY" => Some(Self::Currency),
            _ => None,
        }
    }
}
